runtime: nodejs18

# Instance configuration
instance_class: F2

# Auto-scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables (update with your actual values)
# For production, use Secret Manager instead of hardcoding secrets here
env_variables:
  NODE_ENV: production
  PORT: 8080
  # Add your environment variables here or use Secret Manager
  # GOOGLE_CLIENT_ID: your_client_id
  # GOOGLE_CLIENT_SECRET: your_client_secret
  # GOOGLE_REDIRECT_URI: https://YOUR_PROJECT_ID.appspot.com/api/auth/google/callback
  # GOOGLE_VISION_API_KEY: your_vision_api_key
  # GOOGLE_GEMINI_API_KEY: your_gemini_api_key
  # GOOGLE_PROJECT_ID: your_project_id
  # FIRESTORE_DATABASE_ID: (default)
  # SESSION_SECRET: your_secure_random_secret
  # CLIENT_URL: https://YOUR_PROJECT_ID.appspot.com

# Files to skip during deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?client/node_modules/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.env.*$
  - ^(.*/)?logs/.*$
  - ^(.*/)?uploads/.*$
  - ^(.*/)?\.DS_Store$
  - ^(.*/)?service-account-key\.json$
  - ^(.*/)?\*.*-key\.json$

